spring:
  application:
    name: my-api-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/food-ordering-realm
server:
    port: 8081
